### ISSUE TITLE
Add comment meta-data to post frontmatter

### ISSUE THREAD

**Issue by nfreear** [nfreear/nfreear-blog#19]
Typical example -- [`2009-07-16-improving-the-accessibility-of-uservoice.md`](https://github.com/nfreear/nfreear.github.io/blob/master/_posts/2009-07-16-improving-the-accessibility-of-uservoice.md) - [blog](http://nick.freear.org.uk/2009/07/16/improving-the-accessibility-of-uservoice.html):

```

---
layout: post
title:  Improving the accessibility of UserVoice
date:   2009-07-16 12:01:00
categories:
tags:   accessibility  feedback  javascript  uservoice
x-source:  http://freear.org.uk/content/improving-accessibility-uservoice
x-comment-count: 4
x-comments:
  - id: 3
    by: Scott Rutherford <http://www.uservoice.com> (not verified) | Sat, 18/07/2009 - 17:25
    subject: This is now fixed!
    text: >
      Hi Nick,

      I believe we have now fixed this issue, thanks for bringing it to our attention. Are you still having issues with the main site in Firefox? If so, do you think you could send more information on it to support?

      Thanks, Scott Rutherford, CTO Uservoice

---
```
